### PR TITLE
Lock SMART JS client to version 0.1.12 to avoid breaking changes intr…

### PR DESCRIPTION
**Pull request by nschwertner**
…oduced in later versions

### CODE REVIEW

**Comment by nschwertner** [comment]
A couple of the sample apps are currently broken due to breaking changes introduced in the SMART JS client at https://github.com/smart-on-fhir/client-js/commit/19dbdb163797c28e01822f1b82ee96dd71b57a83 in the fetchAllWithReferences method of fhir.js

**Comment by vlad-ignatov** [comment]
Do you know what those breaking changes are exactly? I wonder if it can be fixed in `client-js` or in `fhir.js`.

**Comment by hansenms** [comment]
https://github.com/smart-on-fhir/sample-apps-stu3/issues/13

Is this problem.

Is the change in `fetchAllWithReferences` intentional? It is now returning a search bundle instead of an arry of results.

**Comment by hansenms** [comment]
I just put up this as an example of another workaround (for one app):

https://github.com/smart-on-fhir/sample-apps-stu3/pull/14

The question is if the breaking change in fhirclient was intentional or not. @vlad-ignatov ?

**Pull request merged**
